// lib/contracts/abis.ts

// UserVault Contract ABI (Complete)
export const USER_VAULT_ABI = [
  {
    type: "constructor",
    stateMutability: "undefined",
    payable: false,
    inputs: [
      { type: "address", name: "_owner" },
      { type: "address", name: "_factory" },
    ],
  },
  {
    type: "error",
    name: "HTSCallFailed",
    inputs: [
      { type: "string", name: "operation" },
      { type: "int32", name: "responseCode" },
    ],
  },
  { type: "error", name: "InsufficientBalance", inputs: [] },
  { type: "error", name: "InvalidAddress", inputs: [] },
  { type: "error", name: "InvalidAmount", inputs: [] },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ type: "address", name: "owner" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ type: "address", name: "account" }],
  },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  { type: "error", name: "SenderNotAssociated", inputs: [] },
  { type: "error", name: "TokenAlreadyAssociated", inputs: [] },
  { type: "error", name: "TokenNotAssociated", inputs: [] },
  {
    type: "event",
    anonymous: false,
    name: "AutoSyncTriggered",
    inputs: [
      { type: "address", name: "token", indexed: true },
      { type: "uint256", name: "timestamp", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "BalanceSynced",
    inputs: [
      { type: "address", name: "token", indexed: true },
      { type: "int64", name: "oldBalance", indexed: false },
      { type: "int64", name: "newBalance", indexed: false },
      { type: "uint256", name: "timestamp", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "HTSOperationFailed",
    inputs: [
      { type: "address", name: "token", indexed: true },
      { type: "int32", name: "responseCode", indexed: false },
      { type: "string", name: "operation", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "OwnershipTransferred",
    inputs: [
      { type: "address", name: "previousOwner", indexed: true },
      { type: "address", name: "newOwner", indexed: true },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "TokenAdded",
    inputs: [
      { type: "address", name: "token", indexed: true },
      { type: "uint256", name: "timestamp", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "TokenAssociated",
    inputs: [
      { type: "address", name: "token", indexed: true },
      { type: "uint256", name: "timestamp", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "TokenDissociated",
    inputs: [
      { type: "address", name: "token", indexed: true },
      { type: "uint256", name: "timestamp", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "TokenRemoved",
    inputs: [
      { type: "address", name: "token", indexed: true },
      { type: "uint256", name: "timestamp", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "TokensReceived",
    inputs: [
      { type: "address", name: "token", indexed: true },
      { type: "int64", name: "amount", indexed: false },
      { type: "address", name: "from", indexed: true },
      { type: "uint256", name: "timestamp", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "TokensWithdrawn",
    inputs: [
      { type: "address", name: "token", indexed: true },
      { type: "int64", name: "amount", indexed: false },
      { type: "address", name: "to", indexed: true },
      { type: "uint256", name: "timestamp", indexed: false },
    ],
  },
  {
    type: "function",
    name: "AUTO_SYNC_THRESHOLD",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "associateToken",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "token" }],
    outputs: [],
  },
  {
    type: "function",
    name: "associateTokens",
    constant: false,
    payable: false,
    inputs: [{ type: "address[]", name: "tokens" }],
    outputs: [],
  },
  {
    type: "function",
    name: "checkTokenAssociation",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "token" }],
    outputs: [{ type: "bool", name: "associated" }],
  },
  {
    type: "function",
    name: "deposit",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "token" },
      { type: "int64", name: "amount" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "dissociateToken",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "token" }],
    outputs: [],
  },
  {
    type: "function",
    name: "emergencyRecover",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "token" },
      { type: "int64", name: "amount" },
      { type: "address", name: "to" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "factory",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "getAllSupportedTokens",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address[]", name: "tokens" }],
  },
  {
    type: "function",
    name: "getBalance",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "token" }],
    outputs: [{ type: "int64", name: "balance" }],
  },
  {
    type: "function",
    name: "getHBARBalance",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "balance" }],
  },
  {
    type: "function",
    name: "getLastSyncTimestamp",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "token" }],
    outputs: [{ type: "uint256", name: "timestamp" }],
  },
  {
    type: "function",
    name: "getSupportedTokenCount",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "count" }],
  },
  {
    type: "function",
    name: "getTrackedBalance",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "token" }],
    outputs: [{ type: "int64", name: "balance" }],
  },
  {
    type: "function",
    name: "isAccountAssociatedWithToken",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [
      { type: "address", name: "account" },
      { type: "address", name: "token" },
    ],
    outputs: [{ type: "bool", name: "associated" }],
  },
  {
    type: "function",
    name: "isTokenAssociated",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "" }],
    outputs: [{ type: "bool", name: "" }],
  },
  {
    type: "function",
    name: "isTokenSupported",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "" }],
    outputs: [{ type: "bool", name: "" }],
  },
  {
    type: "function",
    name: "lastSyncTimestamp",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "" }],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "needsSync",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "token" }],
    outputs: [{ type: "bool", name: "needed" }],
  },
  {
    type: "function",
    name: "owner",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "removeToken",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "token" }],
    outputs: [],
  },
  {
    type: "function",
    name: "renounceOwnership",
    constant: false,
    payable: false,
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "supportedTokens",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint256", name: "" }],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "syncAllTokens",
    constant: false,
    payable: false,
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "syncTokenBalance",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "token" }],
    outputs: [],
  },
  {
    type: "function",
    name: "tokenBalances",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "" }],
    outputs: [{ type: "int64", name: "" }],
  },
  {
    type: "function",
    name: "transferOwnership",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "newOwner" }],
    outputs: [],
  },
  {
    type: "function",
    name: "withdrawHBAR",
    constant: false,
    payable: false,
    inputs: [
      { type: "uint256", name: "amount" },
      { type: "address", name: "to" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "withdrawTo",
    constant: false,
    payable: false,
    inputs: [
      { type: "address", name: "token" },
      { type: "int64", name: "amount" },
      { type: "address", name: "to" },
    ],
    outputs: [],
  },
  { type: "receive", stateMutability: "payable" },
] as const;

// VolatilityIndex Contract ABI (Complete)
export const VOLATILITY_INDEX_ABI = [
  {
    type: "constructor",
    stateMutability: "undefined",
    payable: false,
    inputs: [{ type: "address", name: "pythContract" }],
  },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ type: "address", name: "owner" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ type: "address", name: "account" }],
  },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  {
    type: "event",
    anonymous: false,
    name: "FeedAdded",
    inputs: [
      { type: "bytes32", name: "priceFeedId", indexed: true },
      { type: "uint256", name: "timestamp", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "FeedRemoved",
    inputs: [
      { type: "bytes32", name: "priceFeedId", indexed: true },
      { type: "uint256", name: "timestamp", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "OwnershipTransferred",
    inputs: [
      { type: "address", name: "previousOwner", indexed: true },
      { type: "address", name: "newOwner", indexed: true },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "PriceStalenessUpdated",
    inputs: [
      { type: "uint256", name: "oldValue", indexed: false },
      { type: "uint256", name: "newValue", indexed: false },
      { type: "uint256", name: "timestamp", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "PythContractUpdated",
    inputs: [
      { type: "address", name: "oldPyth", indexed: false },
      { type: "address", name: "newPyth", indexed: false },
      { type: "uint256", name: "timestamp", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "UpdaterAuthorized",
    inputs: [
      { type: "address", name: "updater", indexed: true },
      { type: "uint256", name: "timestamp", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "UpdaterRevoked",
    inputs: [
      { type: "address", name: "updater", indexed: true },
      { type: "uint256", name: "timestamp", indexed: false },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "VolatilityUpdated",
    inputs: [
      { type: "bytes32", name: "priceFeedId", indexed: true },
      { type: "uint256", name: "volatilityBps", indexed: false },
      { type: "int64", name: "price", indexed: false },
      { type: "uint64", name: "confidence", indexed: false },
      { type: "int32", name: "expo", indexed: false },
      { type: "uint256", name: "timestamp", indexed: false },
    ],
  },
  {
    type: "function",
    name: "MAX_VOLATILITY_BPS",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "authorizeUpdater",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "updater" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getCurrentPrice",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "bytes32", name: "priceFeedId" }],
    outputs: [
      { type: "int64", name: "price" },
      { type: "int32", name: "expo" },
      { type: "uint64", name: "confidence" },
    ],
  },
  {
    type: "function",
    name: "getHBARBalance",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "balance" }],
  },
  {
    type: "function",
    name: "getLastUpdate",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "bytes32", name: "priceFeedId" }],
    outputs: [{ type: "uint256", name: "timestamp" }],
  },
  {
    type: "function",
    name: "getNormalizedPrice",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "bytes32", name: "priceFeedId" }],
    outputs: [{ type: "uint256", name: "normalizedPrice" }],
  },
  {
    type: "function",
    name: "getSupportedFeedCount",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "count" }],
  },
  {
    type: "function",
    name: "getSupportedFeeds",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "bytes32[]", name: "feeds" }],
  },
  {
    type: "function",
    name: "getVolatility",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "bytes32", name: "priceFeedId" }],
    outputs: [{ type: "uint256", name: "volatilityBps" }],
  },
  {
    type: "function",
    name: "getVolatilityData",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "bytes32", name: "priceFeedId" }],
    outputs: [
      {
        type: "tuple",
        name: "data",
        components: [
          { type: "uint256", name: "volatilityBps" },
          { type: "int64", name: "price" },
          { type: "uint64", name: "confidence" },
          { type: "int32", name: "expo" },
          { type: "uint256", name: "timestamp" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "isAuthorizedUpdater",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "" }],
    outputs: [{ type: "bool", name: "" }],
  },
  {
    type: "function",
    name: "isFeedSupported",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "bytes32", name: "" }],
    outputs: [{ type: "bool", name: "" }],
  },
  {
    type: "function",
    name: "isSupported",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "bytes32", name: "priceFeedId" }],
    outputs: [{ type: "bool", name: "supported" }],
  },
  {
    type: "function",
    name: "isVolatilityStale",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [
      { type: "bytes32", name: "priceFeedId" },
      { type: "uint256", name: "stalenessThreshold" },
    ],
    outputs: [{ type: "bool", name: "isStale" }],
  },
  {
    type: "function",
    name: "maxPriceStaleness",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
  },
  {
    type: "function",
    name: "owner",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "pyth",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
  {
    type: "function",
    name: "removeFeed",
    constant: false,
    payable: false,
    inputs: [{ type: "bytes32", name: "priceFeedId" }],
    outputs: [],
  },
  {
    type: "function",
    name: "renounceOwnership",
    constant: false,
    payable: false,
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "revokeUpdater",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "updater" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setMaxPriceStaleness",
    constant: false,
    payable: false,
    inputs: [{ type: "uint256", name: "newStaleness" }],
    outputs: [],
  },
  {
    type: "function",
    name: "supportedFeeds",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint256", name: "" }],
    outputs: [{ type: "bytes32", name: "" }],
  },
  {
    type: "function",
    name: "transferOwnership",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "newOwner" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updatePythContract",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "newPyth" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateVolatility",
    constant: false,
    stateMutability: "payable",
    payable: true,
    inputs: [
      { type: "bytes[]", name: "priceUpdate" },
      { type: "bytes32", name: "priceFeedId" },
      { type: "uint256", name: "volatilityBps" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "updateVolatilityBatch",
    constant: false,
    stateMutability: "payable",
    payable: true,
    inputs: [
      { type: "bytes[]", name: "priceUpdate" },
      { type: "bytes32[]", name: "priceFeedIds" },
      { type: "uint256[]", name: "volatilitiesBps" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "volatilityData",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "bytes32", name: "" }],
    outputs: [
      { type: "uint256", name: "volatilityBps" },
      { type: "int64", name: "price" },
      { type: "uint64", name: "confidence" },
      { type: "int32", name: "expo" },
      { type: "uint256", name: "timestamp" },
    ],
  },
  {
    type: "function",
    name: "withdrawHBAR",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "to" }],
    outputs: [],
  },
  { type: "receive", stateMutability: "payable" },
] as const;

export const PRICE_FEED_IDS = {
  // HBAR/USD - Hedera
  HBAR_USD: "0xf2ef5dc6156e6cdccda6c315f3fc6de2bf37e9aecbc9b5efc51de98096c3e7c6" as `0x${string}`,
  
  // Alternative major pairs (for reference)
  BTC_USD: "0xf9c0172ba10dfa4d19088d94f5bf61d3b54d5bd7483a322a982e1373ee8ea31b" as `0x${string}`,
  ETH_USD: "0xca80ba6dc32e08d06f1aa886011eed1d77c77be9eb761cc10d72b7d0a2fd57a6" as `0x${string}`,
  WETH_USD: "0x86d196443d86a992f6c4ce38779cdfa36b649e43052ef8bedbe0b503029a94c2" as `0x${string}`,
  USDC_USD: "0x41f3625971ca2ed2263e78573fe5ce23e13d2558ed3f2e47ab0f84fb9e7ae722" as `0x${string}`,
} as const;

// Default price feed ID for the app (HBAR/USD)
export const DEFAULT_PRICE_FEED_ID = PRICE_FEED_IDS.HBAR_USD;
// Contract addresses
export const CONTRACT_ADDRESSES = {
  USER_VAULT: "0xaffc3a3822636804fb5ea3ffaff478b6a2023cd7" as `0x${string}`, // 0.0.7213953
  VOLATILITY_INDEX:
    "0xfc982a861622997f2068921e38f753eee6be0dde" as `0x${string}`, // 0.0.7213992
} as const;
